config/routes.rb
Rails.application.routes.draw do
 scope "(:locale)" do 
  root   to: 'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
 
   resources :users do
    member do
      get :following, :followers, :dog
    end
  end

    resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="www.leedsbeckett.ac.uk/">Design Pattern and Web Application</a>
    by <a href="">Krishna M Chaudhary (C7191646)</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(:help), help_path %></li>
      <li><%= link_to t(:contact), contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.fa.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
    
    
      <ul class="nav navbar-nav navbar-left" style="margin-top: 20px;">
       
        
        <% if logged_in? %>
         
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%=t :account %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu" style="margin-top:20px">
              <li><%= link_to t(:dogs), dog_user_path(current_user) %></li>
               <li><%= link_to t(:profile), current_user %></li>
              <li><%= link_to t(:settings), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(:log_out), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
           <li><%= link_to t(:users), users_path %></li>
        <% else %>
          <li><%= link_to t(:log_in), login_path %></li>
        <% end %>
         <li><%= link_to t(:about),   about_path %></li>
         <li><%= link_to t(:home), root_path %></li>
       
      </ul>
      
      <div class="menu" style="margin:0px 0px 0px 7%;float: right;" lang = <%= I18n.locale %> dir= <%= @local_dir %> >
        <%= link_to image_tag("logo.jpg", alt: "Leeds Beckett University",style:"width:120px"),
              root_path,id: "logo" %>
        <ul class="vertical menu" style="list-style-type: none;position: absolute;

margin: 57px 95px;">
          <li>
              <%= link_to image_tag("flags/UK_Flag.png", border: 0, title:"English"), request.url.gsub(/((\/(en)\/)|(\/(ne)\/)|(\/(fa)\/)|(\/(th)\/))|(\/(en))|(\/(ne))|(\/(fa))|(\/(th))/, "/en/"), {class: 'flag-icon'} %>
              <%= link_to image_tag("flags/NEPAL_Flag.png", border: 0, title:"नेपाली", style:"width: 20px;padding-bottom: 17px;"), request.url.gsub(/((\/(en)\/)|(\/(ne)\/)|(\/(fa)\/)|(\/(th)\/))|(\/(en))|(\/(ne))|(\/(fa))|(\/(th))/, "/ne/"), {class: 'flag-icon'} %>
              <%= link_to image_tag("flags/IRAN_Flag.png", border: 0, title:"فارسی"), request.url.gsub(/((\/(en)\/)|(\/(ne)\/)|(\/(fa)\/)|(\/(th)\/))|(\/(en))|(\/(ne))|(\/(fa))|(\/(th))/, "/fa/"), {class: 'flag-icon'} %>
              <%= link_to image_tag("flags/THAILAND_Flag.png", border: 0, title:"ไทย"), request.url.gsub(/((\/(en)\/)|(\/(ne)\/)|(\/(fa)\/)|(\/(th)\/))|(\/(en))|(\/(ne))|(\/(fa))|(\/(th))/, "/th/"), {class: 'flag-icon'} %>
          </li>
          
        </ul>
        
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
    <%= link_to image_tag("logo.jpg", alt: "Leeds Beckett University",style:"width:120px"),
              root_path,id: "logo" %>
    
      <ul class="nav navbar-nav navbar-right" style="margin-top: 20px;">
        <li><%= link_to t(:home), root_path %></li>
        <li><%= link_to t(:about),   about_path %></li>
        
        <% if logged_in? %>
          <li><%= link_to t(:users), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%=t :account %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu" style="margin-top:20px">
              <li><%= link_to t(:dogs), dog_user_path(current_user) %></li>
               <li><%= link_to t(:profile), current_user %></li>
              <li><%= link_to t(:settings), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(:log_out), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(:log_in), login_path %></li>
        <% end %>
      </ul>
      <div class="menu" style="margin: 58px 0px 0px 7%;position: absolute;" lang = <%= I18n.locale %> dir= <%= @local_dir %> >
        <ul class="vertical menu" style="list-style-type: none;">
          <li>
              <%= link_to image_tag("flags/UK_Flag.png", border: 0, title:"English"), request.url.gsub(/((\/(en)\/)|(\/(ne)\/)|(\/(fa)\/)|(\/(th)\/))|(\/(en))|(\/(ne))|(\/(fa))|(\/(th))/, "/en/"), {class: 'flag-icon'} %>
              <%= link_to image_tag("flags/NEPAL_Flag.png", border: 0, title:"नेपाल", style:"width: 20px;padding-bottom: 17px;"), request.url.gsub(/((\/(en)\/)|(\/(ne)\/)|(\/(fa)\/)|(\/(th)\/))|(\/(en))|(\/(ne))|(\/(fa))|(\/(th))/, "/ne/"), {class: 'flag-icon'} %>
              <%= link_to image_tag("flags/IRAN_Flag.png", border: 0, title:"فارسی"), request.url.gsub(/((\/(en)\/)|(\/(ne)\/)|(\/(fa)\/)|(\/(th)\/))|(\/(en))|(\/(ne))|(\/(fa))|(\/(th))/, "/fa/"), {class: 'flag-icon'} %>
              <%= link_to image_tag("flags/THAILAND_Flag.png", border: 0, title:"ไทย"), request.url.gsub(/((\/(en)\/)|(\/(ne)\/)|(\/(fa)\/)|(\/(th)\/))|(\/(en))|(\/(ne))|(\/(fa))|(\/(th))/, "/th/"), {class: 'flag-icon'} %>
          </li>
          
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container" style=" margin-top: 60px;">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>